import Foundation

await directoryLoaderTests()
await fileSorterTests()
await navigationHistoryTests()
await directoryWatcherTests()
await paneStateTests()
await ancestorChainTests()
await filterPresetsTests()
await filterEngineTests()
await paneFilterTests()
await tabStateTests()
await sessionStateTests()
await recentsTests()
await scannerTests()
await paletteModelTests()
await previewRendererTests()
await hoverPreviewModelTests()
await fileOperationTests()
await undoTests()
await renamePlanTests()
await batchToolsTests()
await paneBatchToolsTests()
await fuzzyMatcherTests()

finish()
